"""Finalize the autogenerated initial migration.

1. create the required extensions first;
2. create tables in an acyclic topological order (the ledger <-> salary_records
   foreign keys form a real cycle, so they are deferred to ALTER TABLE);
3. make the downgrade the exact reverse.
"""

from __future__ import annotations

import glob
import re
import sys

sys.path.insert(0, ".")

import app.models_registry  # noqa: F401
from app.core.db import Base

DEFERRED = {
    ("employee_ledger_entries", "salary_records"),
    ("salary_records", "employee_ledger_entries"),
}

DEFERRED_INLINE = {
    "employee_ledger_entries": "    sa.ForeignKeyConstraint(['salary_record_id'], ['salary_records.id'], name='fk_ledger_salary_record'),\n",
    "salary_records": "    sa.ForeignKeyConstraint(['ledger_entry_id'], ['employee_ledger_entries.id'], name='fk_salary_records_ledger_entry'),\n",
}

EXTENSIONS = (
    "    # Required extensions (docs/02_DATABASE.md section 21):\n"
    "    #   citext      -> users.email case-insensitive uniqueness\n"
    "    #   btree_gist  -> EXCLUDE constraints (DB-7 leave overlap, DB-8 compensation)\n"
    "    #   pgcrypto    -> gen_random_uuid()\n"
    '    op.execute("CREATE EXTENSION IF NOT EXISTS citext")\n'
    '    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")\n'
    '    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")\n'
)

CREATE_FKS = (
    "    # Deferred foreign keys breaking the employee_ledger_entries <-> salary_records cycle.\n"
    "    op.create_foreign_key('fk_ledger_salary_record', 'employee_ledger_entries', 'salary_records', ['salary_record_id'], ['id'])\n"
    "    op.create_foreign_key('fk_salary_records_ledger_entry', 'salary_records', 'employee_ledger_entries', ['ledger_entry_id'], ['id'])\n"
)

DROP_FKS = (
    "    op.drop_constraint('fk_salary_records_ledger_entry', 'salary_records', type_='foreignkey')\n"
    "    op.drop_constraint('fk_ledger_salary_record', 'employee_ledger_entries', type_='foreignkey')\n"
)


def topological_order() -> list[str]:
    tables = Base.metadata.tables
    deps: dict[str, set[str]] = {name: set() for name in tables}
    for name, table in tables.items():
        for fk in table.foreign_keys:
            target = fk.column.table.name
            if target != name and (name, target) not in DEFERRED:
                deps[name].add(target)

    order: list[str] = []
    visited: set[str] = set()

    def visit(node: str, stack: set[str]) -> None:
        if node in visited:
            return
        stack.add(node)
        for dep in sorted(deps[node]):
            if dep not in stack:
                visit(dep, stack)
        stack.discard(node)
        visited.add(node)
        order.append(node)

    for name in sorted(tables):
        visit(name, set())
    return order


def main() -> None:
    path = glob.glob("app/migrations/versions/*_initial_schema.py")[0]
    text = open(path, encoding="utf-8").read()

    for table, line in DEFERRED_INLINE.items():
        assert line in text, "missing inline FK for " + table
        text = text.replace(line, "", 1)

    marker = "\n    # ### commands auto generated by Alembic - please adjust! ###\n"
    end_marker = "\n    # ### end Alembic commands ###\n"
    m_start = text.index(marker)
    m_end = text.index(end_marker)
    head = text[: m_start + 1]
    body = text[m_start + len(marker) : m_end + 1]
    tail = text[m_end + len(end_marker) :]

    starts = [m.start() for m in re.finditer(r"    op\.create_table\('([a-z_]+)',\n", body)]
    names = [re.match(r"    op\.create_table\('([a-z_]+)',\n", body[s:]).group(1) for s in starts]
    blocks: dict[str, str] = {}
    for i, (start, name) in enumerate(zip(starts, names)):
        end = starts[i + 1] if i + 1 < len(starts) else len(body)
        blocks[name] = body[start:end]
    assert len(blocks) == len(names), "duplicate table block detected"

    order = topological_order()
    assert set(blocks) == set(order), (
        f"mismatch: missing={sorted(set(order) - set(blocks))} extra={sorted(set(blocks) - set(order))}"
    )

    rebuilt = ["    # ### commands auto generated by Alembic - please adjust! ###\n"]
    rebuilt.append(EXTENSIONS)
    for name in order:
        rebuilt.append(blocks[name])
    rebuilt.append("\n" + CREATE_FKS)
    rebuilt.append("    # ### end Alembic commands ###\n")

    text = head + "".join(rebuilt) + tail
    text = text.replace("def downgrade() -> None:\n", "def downgrade() -> None:\n" + DROP_FKS, 1)
    open(path, "w", encoding="utf-8").write(text)

    print("tables reordered:", len(order))
    print("first:", order[:6])
    print("last:", order[-4:])


if __name__ == "__main__":
    main()