"""Rewrite the autogenerated initial migration so table creation is acyclic.

The ledger <-> salary_records foreign keys form a genuine cycle. They are removed
from the inline CREATE TABLE blocks and added afterwards with ALTER TABLE, which
is also how a reviewed migration should express them.
"""

from __future__ import annotations

import glob
import re
import sys

sys.path.insert(0, ".")

import app.models_registry  # noqa: F401
from app.core.db import Base

DEFERRED = {
    ("employee_ledger_entries", "salary_records"),
    ("salary_records", "employee_ledger_entries"),
}

DEFERRED_LINES = [
    "    sa.ForeignKeyConstraint(['salary_record_id'], ['salary_records.id'], name='fk_ledger_salary_record'),\n",
    "    sa.ForeignKeyConstraint(['ledger_entry_id'], ['employee_ledger_entries.id'], name='fk_salary_records_ledger_entry'),\n",
]

CREATE_FK_LINES = [
    "    op.create_foreign_key('fk_ledger_salary_record', 'employee_ledger_entries', 'salary_records', ['salary_record_id'], ['id'])\n",
    "    op.create_foreign_key('fk_salary_records_ledger_entry', 'salary_records', 'employee_ledger_entries', ['ledger_entry_id'], ['id'])\n",
]

DROP_FK_LINES = [
    "    op.drop_constraint('fk_salary_records_ledger_entry', 'salary_records', type_='foreignkey')\n",
    "    op.drop_constraint('fk_ledger_salary_record', 'employee_ledger_entries', type_='foreignkey')\n",
]


def topological_order() -> list[str]:
    tables = Base.metadata.tables
    deps: dict[str, set[str]] = {name: set() for name in tables}
    for name, table in tables.items():
        for fk in table.foreign_keys:
            target = fk.column.table.name
            if target != name and (name, target) not in DEFERRED:
                deps[name].add(target)

    order: list[str] = []
    visited: set[str] = set()

    def visit(node: str, stack: set[str]) -> None:
        if node in visited:
            return
        stack.add(node)
        for dep in sorted(deps[node]):
            if dep not in stack:
                visit(dep, stack)
        stack.discard(node)
        visited.add(node)
        order.append(node)

    for name in sorted(tables):
        visit(name, set())
    return order


def main() -> None:
    path = glob.glob("app/migrations/versions/*_initial_schema.py")[0]
    text = open(path, encoding="utf-8").read()

    for line in DEFERRED_LINES:
        assert line in text, "deferred FK line not found: " + line.strip()
        text = text.replace(line, "", 1)

    # Split the upgrade() body into create_table blocks.
    body_start = text.index("# ### commands auto generated by Alembic - please adjust! ###\n")
    body_end = text.index("# ### end Alembic commands ###")
    head = text[:body_start]
    body = text[body_start:body_end]
    tail = text[body_end:]

    pattern = re.compile(r"    op\.create_table\('([a-z_]+)',\n(?:.*?\n)*?    \)\n\n", re.MULTILINE)
    blocks: dict[str, str] = {}
    leftovers: list[str] = []
    cursor = 0
    for match in pattern.finditer(body):
        leftovers.append(body[cursor:match.start()])
        blocks[match.group(1)] = match.group(0)
        cursor = match.end()
    leftovers.append(body[cursor:])
    leftover = "".join(leftovers).strip()

    order = topological_order()
    missing = set(blocks) - set(order)
    assert not missing, f"tables missing from metadata: {sorted(missing)}"

    rebuilt = ["    # ### commands auto generated by Alembic - please adjust! ###\n"]
    if leftover:
        rebuilt.append(leftover + "\n")
    for name in order:
        if name in blocks:
            rebuilt.append(blocks[name])
    rebuilt.append("\n    # Foreign keys deferred to break the ledger <-> salary_records cycle.\n")
    rebuilt.extend(CREATE_FK_LINES)

    text = head + "".join(rebuilt) + tail

    # Downgrade must drop the deferred constraints first.
    text = text.replace(
        "def downgrade() -> None:\n",
        "def downgrade() -> None:\n" + "".join(DROP_FK_LINES),
        1,
    )
    open(path, "w", encoding="utf-8").write(text)
    print("reordered", len(order), "tables in", path)
    print("first 8:", order[:8])


if __name__ == "__main__":
    main()